
import type { Product, User, Order, Address, OrderItem } from '@/types';

export const mockProducts: Product[] = [
  {
    id: 'prod-47231',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS",
    description: 'prod_47231',
    price: 245,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_cu_miel_adult_small_and_mini_breeds_1_7_kg-47231.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 50,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    coatColor: 'White',
    weight: 1.7
  },
  {
    id: 'prod-45834',
    name: "Nature's Protection HEALTHY SKIN & COAT",
    description: 'prod_45834',
    price: 350,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_healthy_skin_coat_2_kg-45834.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    purpose: 'Skin & Coat',
    weight: 2
  },
  {
    id: 'prod-45835',
    name: "Nature's Protection HEALTHY GROWTH",
    description: 'prod_45835',
    price: 350,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_healthy_growth_2_kg-45835.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 35,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    purpose: 'Healthy Growth',
    weight: 2
  },
  {
    id: 'prod-45829',
    name: "Nature's Protection MINI ADULT",
    description: 'prod_45829',
    price: 295,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_mini_adult_2_kg-45829.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 60,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Poultry',
    weight: 2
  },
  {
    id: 'prod-45830',
    name: "Nature's Protection MINI JUNIOR",
    description: 'prod_45830',
    price: 295,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_mini_junior_2_kg-45830.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 55,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    weight: 2
  },
  {
    id: 'prod-45671',
    name: "Nature's Protection LIFESTYLE GRAIN FREE SALMON WITH KRILL STERILISED ADULT ALL BREEDS",
    description: 'prod_45671',
    price: 265,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_lifestyle_grain_free_salmon_with_krill_sterilised_adult_all_breeds_1_5_kg-45671.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 30,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    purpose: 'Sterilised',
    weight: 1.5
  },
  {
    id: 'prod-47592',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE INSECTS JUNIOR SMALL AND MINI BREEDS",
    description: 'prod_47592',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_insecte_junior_small_and_mini_breeds_1_5_kg-47592.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 25,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Junior',
    flavour: 'Insect',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: 'prod-45662',
    name: "Nature's Protection MINI EXTRA SALMON",
    description: 'prod_45662',
    price: 295,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_mini_extra_somon_2_kg-45662.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 45,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    weight: 2
  },
  {
    id: 'prod-45661',
    name: "Nature's Protection MINI ADULT LAMB",
    description: 'prod_45661',
    price: 295,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_mini_adult_miel_2_kg-45661.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 50,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    weight: 2
  },
  {
    id: 'prod-45666',
    name: "Nature's Protection LAMB",
    description: 'prod_45666',
    price: 980,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_lamb_12_kg-45666.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 20,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    weight: 12
  },
  {
    id: 'prod-45667',
    name: "Nature's Protection MAXI JUNIOR",
    description: 'prod_45667',
    price: 990,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_maxi_junior_12_kg-45667.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 15,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    weight: 12
  },
  {
    id: 'prod-45663',
    name: "Nature's Protection ADULT POULTRY",
    description: 'prod_45663',
    price: 850,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_adult_pasare_12_kg-45663.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 22,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Adult',
    flavour: 'Poultry',
    weight: 12
  },
  {
    id: 'prod-70012',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS STARTER ALL BREEDS",
    description: 'prod_70012',
    price: 120,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_starter_all_breeds_400_g-70012.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 30,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Starter',
    flavour: 'Poultry',
    coatColor: 'White',
    weight: 0.4
  },
  {
    id: 'prod-70010',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE SALMON JUNIOR SMALL AND MINI BREEDS",
    description: 'prod_70010',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_salmon_junior_small_and_mini_breeds_1_5_kg-70010.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 28,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Junior',
    flavour: 'Salmon',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: 'prod-63999',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE HERRING ADULT SMALL AND MINI BREEDS",
    description: 'prod_63999',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_herring_adult_small_and_mini_breeds_1_5_kg-63999.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 33,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Herring',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: 'prod-15119',
    name: "Nature's Protection SUPERIOR CARE RED COAT GRAIN FREE SALMON ADULT SMALL AND MINI BREEDS",
    description: 'prod_15119',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_red_coat_grain_free_salmon_adult_small_and_mini_breeds_1_5_kg-15119.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 20,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    coatColor: 'Red',
    weight: 1.5
  },
  {
    id: 'prod-47230',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE SALMON ADULT SMALL AND MINI BREEDS",
    description: 'prod_47230',
    price: 245,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_cu_somon_adult_small_and_mini_breeds_1_7_kg-47230.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 38,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    coatColor: 'White',
    weight: 1.7
  },
  {
    id: 'prod-47232',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE INSECTS ADULT SMALL AND MINI BREEDS",
    description: 'prod_47232',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_dogs_grain_free_cu_insecte_adult_small_and_mini_breeds_1_5_kg-47232.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Insect',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: 'prod-47654',
    name: "Nature's Protection SUPERIOR CARE RED COAT GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS",
    description: 'prod_47654',
    price: 275,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_red_coat_grain_free_lamb_adult_small_and_mini_breeds_1_5_kg-47654.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 18,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    coatColor: 'Red',
    weight: 1.5
  },
  {
    id: 'prod-45735',
    name: "Nature's Protection SUPERIOR CARE HYPOALLERGENIC DENTAL FRAGRANCE FREE",
    description: 'prod_45735',
    price: 70,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_hypoallergenic_dental_fragrance_free_150_g-45735.jpg',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 100,
    productFor: 'dog',
    purpose: 'Dental Care',
    weight: 0.15
  },
  {
    id: 'prod-171458',
    name: "Nature's Protection Urinary Health",
    description: 'prod_171458',
    price: 130,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_urinary_health_160_g-171458.jpg',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 80,
    productFor: 'dog',
    purpose: 'Urinary Health',
    weight: 0.16
  },
  {
    id: 'prod-17278',
    name: "Nature's Protection SUPERIOR CARE WHITE COAT DENTAL CARE",
    description: 'prod_17278',
    price: 90,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_coat_dental_care_160_g-17278.jpg',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 90,
    productFor: 'dog',
    purpose: 'Dental Care',
    coatColor: 'White',
    weight: 0.16
  },
  {
    id: 'prod-17272',
    name: "Nature's Protection SUPERIOR CARE WHITE COAT HEALTHY HIPS & JOINTS",
    description: 'prod_17272',
    price: 110,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_superior_care_white_coat_healthy_hips_joints_160_g-17272.jpg',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 85,
    productFor: 'dog',
    purpose: 'Hips & Joints',
    coatColor: 'White',
    weight: 0.16
  },
  {
    id: 'prod-47233',
    name: "Nature's Protection LIFESTYLE GRAIN FREE CHICKEN & TURKEY PUPPY ALL BREEDS",
    description: 'prod_47233',
    price: 265,
    imageUrl: 'https://static.petshop.md/photo/nature_s_protection_lifestyle_grain_free_chicken_turkey_puppy_all_breeds_1_5_kg-47233.jpg',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Junior',
    flavour: 'Chicken & Turkey',
    weight: 1.5
  }
];

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(p => p.id === id);
}

export function getProductsByIds(ids: string[]): Product[] {
  return mockProducts.filter(p => ids.includes(p.id));
}

// MOCK DATA - In a real app, this would come from a database.
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'buyer@example.com',
    name: 'Alex Buyer',
    addresses: [
      { id: 'addr-1', street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova', isDefault: true },
      { id: 'addr-2', street: '456 Dog Park Ave', city: 'Balti', postalCode: 'MD-3100', country: 'Moldova', isDefault: false },
    ],
  },
  {
    id: 'admin-1',
    email: 'admin@ecoshop.md',
    name: 'Admin User',
    addresses: [],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: 'user-1',
    orderDate: '2024-04-20T10:30:00Z',
    status: 'Delivered',
    totalAmount: 735.00,
    shippingAddress: { street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova' },
    trackingNumber: 'NP123456789MD',
    items: [
      { productId: 'prod-4', name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS", quantity: 1, price: 245 },
      { productId: 'prod-11', name: "Nature's Protection HEALTHY SKIN & COAT", quantity: 1, price: 350 },
      { productId: 'prod-12', name: 'Nature\'s Protection SUPERIOR CARE HYPOALLERGENIC DENTAL FRAGRANCE FREE', quantity: 2, price: 70 },
    ],
  },
  {
    id: 'ORD-002',
    userId: 'user-1',
    orderDate: '2024-05-10T14:00:00Z',
    status: 'Shipped',
    totalAmount: 560.00,
    shippingAddress: { street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova' },
    trackingNumber: 'NP987654321MD',
    items: [
      { productId: 'prod-6', name: "Nature's Protection LIFESTYLE GRAIN FREE SALMON WITH KRILL STERILISED ADULT ALL BREEDS", quantity: 1, price: 265 },
      { productId: 'prod-7', name: "Nature's Protection MINI EXTRA SALMON", quantity: 1, price: 295 },
    ],
  },
];

    