
import type { Product, User, Order, Address, OrderItem } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS",
    description: '1',
    price: 245,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 50,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    coatColor: 'White',
    weight: 1.7
  },
  {
    id: '2',
    name: "Nature's Protection HEALTHY SKIN & COAT",
    description: '2',
    price: 350,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    purpose: 'Skin & Coat',
    weight: 2
  },
  {
    id: '3',
    name: "Nature's Protection HEALTHY GROWTH",
    description: '3',
    price: 350,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 35,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    purpose: 'Healthy Growth',
    weight: 2
  },
  {
    id: '4',
    name: "Nature's Protection MINI ADULT",
    description: '4',
    price: 295,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 60,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Poultry',
    weight: 2
  },
  {
    id: '5',
    name: "Nature's Protection MINI JUNIOR",
    description: '5',
    price: 295,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 55,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    weight: 2
  },
  {
    id: '6',
    name: "Nature's Protection LIFESTYLE GRAIN FREE SALMON WITH KRILL STERILISED ADULT ALL BREEDS",
    description: '6',
    price: 265,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 30,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    purpose: 'Sterilised',
    weight: 1.5
  },
  {
    id: '7',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE INSECTS JUNIOR SMALL AND MINI BREEDS",
    description: '7',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 25,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Junior',
    flavour: 'Insect',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: '8',
    name: "Nature's Protection MINI EXTRA SALMON",
    description: '8',
    price: 295,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 45,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    weight: 2
  },
  {
    id: '9',
    name: "Nature's Protection MINI ADULT LAMB",
    description: '9',
    price: 295,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 50,
    productFor: 'dog',
    breedSize: 'Small Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    weight: 2
  },
  {
    id: '10',
    name: "Nature's Protection LAMB",
    description: '10',
    price: 980,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 20,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    weight: 12
  },
  {
    id: '11',
    name: "Nature's Protection MAXI JUNIOR",
    description: '11',
    price: 990,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 15,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Junior',
    flavour: 'Poultry',
    weight: 12
  },
  {
    id: '12',
    name: "Nature's Protection ADULT POULTRY",
    description: '12',
    price: 850,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 22,
    productFor: 'dog',
    breedSize: 'Large Breeds',
    lifestage: 'Adult',
    flavour: 'Poultry',
    weight: 12
  },
  {
    id: '13',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS STARTER ALL BREEDS",
    description: '13',
    price: 120,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 30,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Starter',
    flavour: 'Poultry',
    coatColor: 'White',
    weight: 0.4
  },
  {
    id: '14',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE SALMON JUNIOR SMALL AND MINI BREEDS",
    description: '14',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 28,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Junior',
    flavour: 'Salmon',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: '15',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE HERRING ADULT SMALL AND MINI BREEDS",
    description: '15',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 33,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Herring',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: '16',
    name: "Nature's Protection SUPERIOR CARE RED COAT GRAIN FREE SALMON ADULT SMALL AND MINI BREEDS",
    description: '16',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 20,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    coatColor: 'Red',
    weight: 1.5
  },
  {
    id: '17',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE SALMON ADULT SMALL AND MINI BREEDS",
    description: '17',
    price: 245,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 38,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Salmon',
    coatColor: 'White',
    weight: 1.7
  },
  {
    id: '18',
    name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE INSECTS ADULT SMALL AND MINI BREEDS",
    description: '18',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Insect',
    coatColor: 'White',
    weight: 1.5
  },
  {
    id: '19',
    name: "Nature's Protection SUPERIOR CARE RED COAT GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS",
    description: '19',
    price: 275,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 18,
    productFor: 'dog',
    breedSize: 'Small & Mini Breeds',
    lifestage: 'Adult',
    flavour: 'Lamb',
    coatColor: 'Red',
    weight: 1.5
  },
  {
    id: '20',
    name: "Nature's Protection SUPERIOR CARE HYPOALLERGENIC DENTAL FRAGRANCE FREE",
    description: '20',
    price: 70,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 100,
    productFor: 'dog',
    purpose: 'Dental Care',
    weight: 0.15
  },
  {
    id: '21',
    name: "Nature's Protection Urinary Health",
    description: '21',
    price: 130,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 80,
    productFor: 'dog',
    purpose: 'Urinary Health',
    weight: 0.16
  },
  {
    id: '22',
    name: "Nature's Protection SUPERIOR CARE WHITE COAT DENTAL CARE",
    description: '22',
    price: 90,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 90,
    productFor: 'dog',
    purpose: 'Dental Care',
    coatColor: 'White',
    weight: 0.16
  },
  {
    id: '23',
    name: "Nature's Protection SUPERIOR CARE WHITE COAT HEALTHY HIPS & JOINTS",
    description: '23',
    price: 110,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog treats',
    category: 'Treats',
    stock: 85,
    productFor: 'dog',
    purpose: 'Hips & Joints',
    coatColor: 'White',
    weight: 0.16
  },
  {
    id: '24',
    name: "Nature's Protection LIFESTYLE GRAIN FREE CHICKEN & TURKEY PUPPY ALL BREEDS",
    description: '24',
    price: 265,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dog food',
    category: 'Dry Food',
    stock: 40,
    productFor: 'dog',
    breedSize: 'All Breeds',
    lifestage: 'Junior',
    flavour: 'Chicken & Turkey',
    weight: 1.5
  }
];

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(p => p.id === id);
}

export function getProductsByIds(ids: string[]): Product[] {
  return mockProducts.filter(p => ids.includes(p.id));
}

// MOCK DATA - In a real app, this would come from a database.
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'buyer@example.com',
    name: 'Alex Buyer',
    addresses: [
      { id: 'addr-1', street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova', isDefault: true },
      { id: 'addr-2', street: '456 Dog Park Ave', city: 'Balti', postalCode: 'MD-3100', country: 'Moldova', isDefault: false },
    ],
  },
  {
    id: 'admin-1',
    email: 'admin@ecoshop.md',
    name: 'Admin User',
    addresses: [],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: 'user-1',
    orderDate: '2024-04-20T10:30:00Z',
    status: 'Delivered',
    totalAmount: 735.00,
    shippingAddress: { street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova' },
    trackingNumber: 'NP123456789MD',
    items: [
      { productId: '1', name: "Nature's Protection SUPERIOR CARE WHITE DOGS GRAIN FREE LAMB ADULT SMALL AND MINI BREEDS", quantity: 1, price: 245 },
      { productId: '2', name: "Nature's Protection HEALTHY SKIN & COAT", quantity: 1, price: 350 },
      { productId: '20', name: 'Nature\'s Protection SUPERIOR CARE HYPOALLERGENIC DENTAL FRAGRANCE FREE', quantity: 2, price: 70 },
    ],
  },
  {
    id: 'ORD-002',
    userId: 'user-1',
    orderDate: '2024-05-10T14:00:00Z',
    status: 'Shipped',
    totalAmount: 560.00,
    shippingAddress: { street: '123 Pet Lane', city: 'Chisinau', postalCode: 'MD-2001', country: 'Moldova' },
    trackingNumber: 'NP987654321MD',
    items: [
      { productId: '6', name: "Nature's Protection LIFESTYLE GRAIN FREE SALMON WITH KRILL STERILISED ADULT ALL BREEDS", quantity: 1, price: 265 },
      { productId: '8', name: "Nature's Protection MINI EXTRA SALMON", quantity: 1, price: 295 },
    ],
  },
];
